[www]
user  = www-data
group = www-data

listen = 0.0.0.0:9000

pm = dynamic
pm.max_children      = 20
pm.start_servers     = 5
pm.min_spare_servers = 3
pm.max_spare_servers = 10
pm.max_requests      = 500

; Логируем медленные запросы
slowlog           = /dev/stderr
request_slowlog_timeout = 5s

; Передаём переменные окружения в PHP
clear_env = no