api_platform:
    title: 'Avtomaster API'
    description: 'Avtomaster auto mechanic search platform'
    version: '0.0.1'

    use_symfony_listeners: true

    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']
        html: ['text/html']
        mergePatchJson: ['application/merge-patch+json']

    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        pagination:
            items_per_page: 100
            maximum_items_per_page: 100

    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header
