security:
    password_hashers:
        App\Domain\User\Entity\User:
            algorithm: bcrypt
            cost: 12
    providers:
        app_user_provider:
            entity:
                class:    App\Domain\User\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
            pattern:   ^/api
            stateless: true
            provider:  app_user_provider
            jwt: ~
        main:
            lazy: true
            provider: app_user_provider
    access_control:
        - { path: ^/api/v1/auth, roles: PUBLIC_ACCESS }
        - { path: ^/api/v1/health, roles: PUBLIC_ACCESS, methods: [GET] }
        - { path: ^/api/v1/payment/webhook, roles: PUBLIC_ACCESS, methods: [POST] }
        - { path: ^/api/v1/masters, roles: PUBLIC_ACCESS, methods: [GET] }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
