user nginx;
worker_processes auto;
error_log /dev/stderr warn;
pid /var/run/nginx.pid;

events {
    worker_connections 1024;
    multi_accept on;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # Скрываем версию
    server_tokens off;

    # Логи в stdout/stderr для Docker
    log_format json escape=json
        '{'
            '"time":"$time_iso8601",'
            '"method":"$request_method",'
            '"uri":"$request_uri",'
            '"status":$status,'
            '"duration":$request_time,'
            '"ip":"$remote_addr"'
        '}';

    access_log /dev/stdout json;

    sendfile           on;
    tcp_nopush         on;
    keepalive_timeout  65;
    gzip               on;
    gzip_types         text/plain text/css application/json application/javascript;

    include /etc/nginx/conf.d/*.conf;
}
